name: GitHub Secrets

on:
    workflow_dispatch:


jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Print Secret
              run: echo "My secret key ${{secrets.SECRET_KEY}}"
